services:

  # httpd-Apache
  httpd:
    build:
      context: ./docker/httpd/
      dockerfile: Dockerfile
      args:
        - USERNAME=${CONTAINER_USERNAME}
        - UID=${CONTAINER_UID}
        - GID=${CONTAINER_GID}
    user: ${CONTAINER_USERNAME}:${CONTAINER_USERNAME}
    container_name: ${HTTPD_CONTAINER_NAME}
    ports:
      - ${HTTPD_PORT_1}
      - ${HTTPD_PORT_2}
    volumes:
      - ./src:/var/www/html
    env_file:
      - docker/httpd/env/httpd.env
    depends_on:
      - php

  # php-fpm
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
      target: ${BUILD_TARGET_APP}
      args:
        - USERNAME=${CONTAINER_USERNAME}
        - UID=${CONTAINER_UID}
        - GID=${CONTAINER_GID}
    user: ${CONTAINER_USERNAME}:${CONTAINER_USERNAME}
    container_name: ${PHP_CONTAINER_NAME}
    volumes:
      - ./src:/var/www/html
    env_file:
      - docker/php/env/php.env
    expose:
      - "9000"

  # Database
  db:
    build:
      context: ./docker/mysql/
      dockerfile: Dockerfile
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - ./docker/mysql/db-volume:/var/lib/mysql
    ports:
      - ${DB_PORT}
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

  # cache
  redis:
    image: redis:latest